[build]
  # This command is automatically detected by Netlify and does not need to be set.
  # command = "npm run build"
  # publish = ".next"

[build.environment]
  # Disable secrets scanning for specific, known-public keys from Firebase.
  # This is necessary because Next.js embeds NEXT_PUBLIC_ variables in client-side JS.
  SECRETS_SCAN_OMIT_KEYS = [
    "NEXT_PUBLIC_FIREBASE_API_KEY",
    "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN",
    "NEXT_PUBLIC_FIREBASE_PROJECT_ID",
    "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET",
    "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID",
    "NEXT_PUBLIC_FIREBASE_APP_ID"
  ]
